# site properties and page defaults
title: CAMP Lab at TU Delft
subtitle: Where innovation sparkles
description: The CAMP Lab is a research group at TU Delft focusing on advanced materials processing and composite structures.
header: images/background.png
footer: images/background.png
proofer: false

# site social media and other links
links:
  tud_website: https://www.tudelft.nl/en/ae/organisation/departments/aerospace-structures-and-materials
  email: b.caglar@tudelft.nl
  orcid: 0000-0001-7771-7323
  google-scholar: nShlEwMAAAAJ
  github: camp-lab-tud 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_projects
  - scope:
      type: "projects"
    values:
      layout: project

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  # generate page for each project
  projects:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
